import { STORAGE_KEYS } from "./constants";

export const EMBED_STORAGE_KEYS = [
    STORAGE_KEYS.LOCALE,
    STORAGE_KEYS.THEME_MODE,
    STORAGE_KEYS.DARK_MODE,
    STORAGE_KEYS.UPLOAD_ENDPOINT,
    STORAGE_KEYS.CLIENT_TAG_ENABLED,
    STORAGE_KEYS.QUOTE_NOTIFICATION_ENABLED,
    STORAGE_KEYS.IMAGE_COMPRESSION_LEVEL,
    STORAGE_KEYS.VIDEO_COMPRESSION_LEVEL,
    STORAGE_KEYS.MEDIA_FREE_PLACEMENT,
    STORAGE_KEYS.SHOW_MASCOT,
    STORAGE_KEYS.SHOW_FLAVOR_TEXT,
    STORAGE_KEYS.SETTINGS_PREFERENCE_METADATA,
    STORAGE_KEYS.FIRST_VISIT,
    STORAGE_KEYS.SHARED_MEDIA_PROCESSED,
    STORAGE_KEYS.HASHTAG_HISTORY,
] as const;

const EMBED_STORAGE_KEY_SET = new Set<string>(EMBED_STORAGE_KEYS);

export function isAllowedEmbedStorageKey(key: string): boolean {
    return EMBED_STORAGE_KEY_SET.has(key);
}

export function filterAllowedEmbedStorageKeys(keys: string[]): string[] {
    return keys.filter(isAllowedEmbedStorageKey);
}
