export const POST_EDITOR_LINE_HEIGHT_PX = 30;
export const POST_EDITOR_VERTICAL_PADDING_PX = 32;
export const POST_EDITOR_MIN_LINES = 4;
export const POST_EDITOR_COMPACT_MIN_LINES = 2;

export const POST_EDITOR_MIN_HEIGHT =
    POST_EDITOR_LINE_HEIGHT_PX * POST_EDITOR_MIN_LINES +
    POST_EDITOR_VERTICAL_PADDING_PX;
export const POST_EDITOR_COMPACT_MIN_HEIGHT =
    POST_EDITOR_LINE_HEIGHT_PX * POST_EDITOR_COMPACT_MIN_LINES +
    POST_EDITOR_VERTICAL_PADDING_PX;
